# Test configuration for Stargate with dynamic configuration source
server:
  address: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# Configuration source (for data plane routing configuration)
config:
  source:
    # Configuration source driver: "file" or "etcd"
    driver: "file"
    # Polling interval for file source (ignored for etcd)
    poll_interval: 1s
    # File source configuration
    file:
      # Path to the routing configuration file
      path: "routes.yaml"
      # How often to check for file changes
      poll_interval: 1s
    # Etcd source configuration (not used when driver is "file")
    etcd:
      # Etcd endpoints
      endpoints:
        - "localhost:2379"
      # Etcd key to watch for routing configuration
      key: "/stargate/routes"
      # Connection timeout
      timeout: 5s
      # TLS configuration
      tls:
        enabled: false
        cert_file: ""
        key_file: ""
        ca_file: ""
      # Authentication
      username: ""
      password: ""

# Proxy configuration
proxy:
  enabled: true
  timeout: 30s
  keep_alive: 30s
  max_idle_conns: 100
  max_idle_conns_per_host: 10

# Load balancer configuration
load_balancer:
  enabled: true
  default_algorithm: "round_robin"

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Metrics configuration
metrics:
  enabled: true
  address: ":9090"
  path: "/metrics"

# Store configuration (for control plane)
store:
  type: "memory"
  key_prefix: "/stargate/config"
  watch: false
