# Test configuration for WASM Plugin Integration
# This configuration sets up the test scenario for BIC-CL-02

server:
  address: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  max_header_bytes: 1048576

# WASM Plugin Integration Configuration for Testing
wasm:
  enabled: true
  plugins:
    # Header modifier plugin
    - id: "header-modifier"
      name: "Header Modifier Plugin"
      path: "wasm-plugins/header-modifier.wasm"
      required: false
  rules:
    # Test rule: /api/wasm-test
    # This rule demonstrates WASM plugin execution for request processing
    - id: "wasm-test-rule"
      path: "/api/wasm-test"
      method: "POST"
      plugins:
        - "header-modifier"

    # Test rule: /api/transform with WASM processing
    - id: "transform-wasm-rule"
      path: "/api/transform"
      method: "POST"
      headers:
        X-WASM-Process: "true"
      plugins:
        - "header-modifier"

    # Test rule: catch-all for testing
    - id: "catch-all-wasm-rule"
      path: "/api/plugin-test"
      plugins:
        - "header-modifier"

# Minimal middleware configuration for testing
auth:
  enabled: false

cors:
  enabled: true
  allowed_origins: ["*"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["Content-Type", "Authorization", "X-WASM-Process"]

rate_limit:
  enabled: false

circuit_breaker:
  enabled: false

aggregator:
  enabled: false

serverless:
  enabled: false

ip_acl:
  enabled: false

header_transform:
  enabled: false

mock_response:
  enabled: false

grpc_web:
  enabled: false

traffic_mirror:
  enabled: false

logging:
  access_log:
    enabled: true
    format: "json"
    output: "stdout"
    fields:
      - "timestamp"
      - "method"
      - "path"
      - "status"
      - "duration"
      - "size"

metrics:
  enabled: true
  prometheus:
    enabled: true
    path: "/metrics"
    port: 9090

tracing:
  enabled: false

# Proxy configuration
proxy:
  buffer_size: 32768
  dial_timeout: 10s
  keep_alive: 30s
  max_idle_conns: 100
  max_idle_conns_per_host: 10
  idle_conn_timeout: 90s

# Load balancer configuration
load_balancer:
  default_algorithm: "round_robin"
  health_check_interval: 30s

# Store configuration (not needed for this test)
store:
  type: "memory"

# Sync configuration (not needed for this test)
sync:
  interval: 30s

# Admin API configuration (for monitoring)
admin_api:
  enabled: true
  address: ":8081"
  auth:
    enabled: false

# Routes and upstreams - Add a simple upstream for testing
routes:
  config_file: ""
  auto_reload: false

upstreams:
  config_file: ""
  auto_reload: false
  defaults:
    algorithm: "round_robin"
    health_check:
      active:
        enabled: false
      passive:
        enabled: false

# Add inline route and upstream configuration for testing
inline_config:
  routes:
    - id: "wasm-test-route"
      path: "/api/wasm-test"
      methods: ["POST"]
      upstream: "test-upstream"
    
    - id: "transform-wasm-route"
      path: "/api/transform"
      methods: ["POST"]
      upstream: "test-upstream"
      
    - id: "plugin-test-route"
      path: "/api/plugin-test"
      methods: ["GET", "POST"]
      upstream: "test-upstream"
  
  upstreams:
    - id: "test-upstream"
      name: "test-upstream"
      algorithm: "round_robin"
      nodes:
        - host: "httpbin.org"
          port: 443
          weight: 1
          scheme: "https"

# Plugins and webhooks (not needed for this test)
plugins:
  enabled: false

webhooks:
  enabled: false
