# Test HTTP Configuration (TLS disabled)
server:
  address: ":8080"
  https_address: ":8443"
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
  timeout: 30s
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 60s
  max_header_bytes: 1048576

# Controller configuration
controller:
  address: ":9090"
  https_address: ":9443"
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
  timeout: 30s
  read_timeout: 10s
  write_timeout: 10s

# Minimal configuration for testing
logging:
  level: "info"
  format: "json"
  output: "stdout"
